---
name: conftest-verify
on:
  pull_request:
    branches: [main]
    paths:
    - '**.rego'
    - .github/workflows/conftest-verify.yaml
    - aqua/conftest.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.6
      - run: github-comment exec -- conftest verify --no-color -p policy/terraform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
