---
name: opa-fmt
on:
  pull_request:
    branches: [main]
    paths:
    - '**.rego'
    - .github/workflows/opa-fmt.yaml
    - aqua/opa.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.6
      - uses: suzuki-shunsuke/github-action-opa-fmt@v0.1.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
