---
name: enable-automerge
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: token
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          permissions: >-
            {"pull_requests": "write", "contents: "write"}
          repositories: >-
            ["${{github.repository}}"]

      - run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --auto --delete-branch "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}} # Use GitHub App to trigger GitHub Actions Workflow by merge commit.
          PR_NUMBER: ${{github.event.pull_request.number}}
