---
# This workflow is optional.
name: opa-fmt
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
    secrets:
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false
jobs:
  opa-fmt:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout private repositories
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.ref}}
          persist-credentials: false

      - id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          # contents:write - Push commits
          permissions: >-
            {"contents": "write"}
          repositories: >-
            ["${{github.event.repository.name}}"]

      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.6
        env:
          AQUA_GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/github-action-opa-fmt@59d2b3726741e2aeb3fc96ba2cbdfd05ae879f28 # v0.1.0
        with:
          github_token: ${{steps.generate_token.outputs.token}}
